# Generated by Django 6.0.3 on 2026-03-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
