# Generated by Django 6.0.3 on 2026-04-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_event_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('FOLLOW', 'Follow'), ('LIKE', 'Like'), ('PAYMENT', 'Payment'), ('COMMENT', 'Comment'), ('ACCIDENT', 'Accident'), ('CONGESTION', 'Congestion'), ('MALFUNCTION', 'Malfunction')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('FOLLOW', 'Follow'), ('LIKE', 'Like'), ('PAYMENT', 'Payment'), ('COMMENT', 'Comment'), ('ACCIDENT', 'Accident'), ('CONGESTION', 'Congestion'), ('MALFUNCTION', 'Malfunction')], max_length=20),
        ),
    ]
